#ifndef LIBEZP2023PLUS_EZP_ERRORS_H
#define LIBEZP2023PLUS_EZP_ERRORS_H

#define EZP_OK 0
#define EZP_ERROR_IO (-1)
#define EZP_ERROR_INVALID_FILE (-2)
#define EZP_FLASH_SIZE_OR_PAGE_INVALID (-3)
#define EZP_LIBUSB_ERROR (-4)
#define EZP_INVALID_DATA_FROM_PROGRAMMER (-5)
#define EZP_FLASH_NOT_DETECTED (-6)
#define EZP_HOTPLUG_UNSUPPORTED (-7)

#endif //LIBEZP2023PLUS_EZP_ERRORS_H
